name: README Continuous Integration Workflow

on:
  push:
    branches: [master]

jobs:
  README-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 17
        
      - name: Tarang74/README-CI
        uses: Tarang74/README-CI@8842cd903057a96c54401d5e4efc275206a66663
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
