name: README Continuous Integration Workflow

on:
  push:
    branches: [master]

jobs:
  README-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Tarang74/README-CI
        uses: Tarang74/README-CI@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
